### ISSUE TITLE
Server Start Error 

### ISSUE THREAD

**Issue by mknverma** [CognirelTech/Quillpad-Server#1]
Today I Tried This Code But I Got Error In This How Can I Get It Solved

os - win7
python - 2.12 

C:\Users\MKNVERMA\Desktop\qu>python startquill_cherry.py
Traceback (most recent call last):
  File "startquill_cherry.py", line 9, in <module>
    from QuillSourceProcessor import QuillSourceProcessor
  File "C:\Users\MKNVERMA\Desktop\qu\QuillSourceProcessor.py", line 6, in <module

> ```
> import QuillLanguage as qlang
> ```
> 
>   File "C:\Users\MKNVERMA\Desktop\qu\QuillLanguage.py", line 17, in <module>
>     from QuillCCart import QuillCKnowledge
> ImportError: No module named QuillCCart

**Comment by cognirel** [comment]
Hi,
Those instructions are for linux and mac. 

For windows, change the line in the instructions in the **installation section** from
`cp QuillCCart.so ../../`
to
`cp QuillCCart.pyd ../../`

and you should be good to go.

**Comment by mknverma** [comment]
Thanks for your response......
but i am having problem in getting multiple translation of word in JSON response like we get on website demo. how i can archive that.

**Comment by cognirel** [comment]
Can you describe the problem in slightly more detail?

`processWordJSON` api call will return a JSON response with all the details needed including options.

Here is a sample JSON response of the API call
`{"twords": [{"optmap": {"हेल्लो": ["ह", "े", "ल्", "ल", "ो"]}, "word": true, "options": ["हेलो", "हेल्लो"]}], "itrans": "हेल्लो", "inString": "hello"}`

**Comment by mknverma** [comment]
but i got this one why ?????????
i used the same default url for this sample 
so why is that deifference
http://localhost:8090/processWordJSON?inString=hello&lang=hindi
{"twords": [{"optmap": {"hello": ["hello"]}, "word": true, "options": ["hello"]}], "itrans": "हेल्लो", "inString": "hello"}

**Comment by sharathpuranik** [comment]
@mknverma If the **optmap** and **options** are missing from the output, it means that the transliteration data is either missing or there was an error while loading this data.

Can you dump the output of the _python run_server_ command here so that I can suggest a solution?

**Comment by saptha** [comment]
@sharathpuranik I too got the same kind of response as that of @mknverma 
Below is the output of python startquill_cherry.py command. Please suggest

 python startquill_cherry.py
Warning: Nevow not found... continuing
Loaded keyboard map for gujarati
Loaded keyboard map for bengali
Loaded keyboard map for telugu
Loaded keyboard map for malayalam
Loaded keyboard map for marathi
Loaded keyboard map for nepali
Loaded keyboard map for kannada
Loaded keyboard map for tamil
Loaded keyboard map for punjabi
Loaded keyboard map for hindi
Loading hindi dictionary... Done (50245 words)
Loaded english dictionary from... dict.txt
Loading .. Hindi_Primary.xml
Loading .. Kannada_Primary.xml
Loading .. Malayalam_Primary.xml
Loading .. Marathi_Primary.xml
Loading .. Tamil_Primary.xml
Loading .. Telugu_Primary.xml
Loading primary rules for gujarati ... done
Loading primary rules for bengali ... done
Loading primary rules for telugu ... done
Loading primary rules for malayalam ... done
Loading primary rules for marathi ... done
Loading primary rules for nepali ... done
Loading primary rules for kannada ... done
Loading primary rules for tamil ... done
Loading primary rules for punjabi ... done
Loading primary rules for hindi ... done
(1045, "Access denied for user 'quill'@'localhost' (using password: YES)")
127.0.0.1 - - [09/Sep/2017:21:57:54] "GET /processWordJSON?inString=hello&lang=hindi HTTP/1.1" 200 135 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [09/Sep/2017:21:57:54] "GET /favicon.ico HTTP/1.1" 200 1406 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:55.0) Gecko/20100101 Firefox/55.0"
(1045, "Access denied for user 'quill'@'localhost' (using password: YES)")

**Comment by sharathpuranik** [comment]
@mknverma @saptha 
I have pushed a couple of fixes to resolve most of the issues affecting Quillpad server. This issue should be resolved.
