### ISSUE TITLE
Instructions for setting up Quillpad server on windows

### ISSUE THREAD

**Issue by pkapare** [CognirelTech/Quillpad-Server#2]
Hi,
Could you please help me with instructions for setting up Quillpad  server on Windows?
Thanks

**Comment by cognirel** [comment]
Hi,
Those instructions given in the documentation are for linux and mac.

For installing on windows, change the line in the instructions in the installation section from
`cp QuillCCart.so ../../`
to
`cp QuillCCart.pyd ../../`

and you should be good to go.

**Comment by sharathpuranik** [comment]
Duplicate of issue #1
