### ISSUE TITLE
Server Start Error - Pyrex.Plex not found

### ISSUE THREAD

**Issue by rajatgarg79** [CognirelTech/Quillpad-Server#4]
I am a noob on Python so this is making things a bit more complex. I hope you can help. This is what I am getting when I try to start the server.
===================================================================
```
ubuntu@ElasticSearch:/var/www/quillpad/CognirelTech-Quillpad-Server-002e98a$ python startquill_cherry.py
Traceback (most recent call last):
  File "startquill_cherry.py", line 9, in <module>
    from QuillSourceProcessor import QuillSourceProcessor
  File "/var/www/quillpad/CognirelTech-Quillpad-Server-002e98a/QuillSourceProcessor.py", line 6, in <module>
    import QuillLanguage as qlang
  File "/var/www/quillpad/CognirelTech-Quillpad-Server-002e98a/QuillLanguage.py", line 10, in <module>
    import Pyrex.Plex
ImportError: No module named Pyrex.Plex
```
===================================================================

pip install Pyrex.Plex leads to the following error - 

```
Downloading/unpacking Pyrex.plex
  Could not find any downloads that satisfy the requirement Pyrex.plex
Cleaning up...
No distributions at all found for Pyrex.plex
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

=================================================================

Same happens for pyrex module or others. Please let me know how to solve this issue

**Comment by sharathpuranik** [comment]
Hi Rajat,

Python pyrex needs to be installed separately. We noticed its missing from the Docs. We will update it soon.

As for the steps involved for Pyrex installation. 
Download: http://www.cosc.canterbury.ac.nz/greg.ewing/python/Pyrex/Pyrex-0.9.9.tar.gz

Untar the file 
`tar -xvf Pyrex-0.9.9.tar.gz`

Go to the new extracted directory

and run
`python setup.py`
