### ISSUE TITLE
Can't able to load Unique words

### ISSUE THREAD

**Issue by magesharumugam** [CognirelTech/Quillpad-Server#5]
Warning: Nevow not found... continuing
Failed to load keyboard map file for gujarati. Exception [Errno 2] No such file or directory: 'unique_gujarati_words.txt'
Failed to load keyboard map file for bengali. Exception [Errno 2] No such file or directory: 'unique_bengali_words.txt'
Failed to load keyboard map file for telugu. Exception [Errno 2] No such file or directory: 'unique_telugu_words.txt'
Failed to load keyboard map file for malayalam. Exception [Errno 2] No such file or directory: 'unique_malayalam_words.txt'
Failed to load keyboard map file for marathi. Exception [Errno 2] No such file or directory: 'unique_marathi_words.txt'
Failed to load keyboard map file for nepali. Exception [Errno 2] No such file or directory: 'unique_nepali_words.txt'
Failed to load keyboard map file for kannada. Exception [Errno 2] No such file or directory: 'unique_kannada_words.txt'
Failed to load keyboard map file for tamil. Exception [Errno 2] No such file or directory: 'unique_tamil_words.txt'
Failed to load keyboard map file for punjabi. Exception [Errno 2] No such file or directory: 'unique_punjabi_words.txt'
Failed to load keyboard map file for hindi. Exception [Errno 2] No such file or directory: 'unique_hindi_words.txt'

> **Traceback (most recent call last):
>   File "startquill_cherry.py", line 9, in <module>
>     from QuillSourceProcessor import QuillSourceProcessor
>   File "/Users/mano-ztga01/Downloads/CognirelTech-Quillpad-Server-002e98a/QuillSourceProcessor.py", line 10, in <module>
>     import primaryHelper
>   File "/Users/MYUSER/Downloads/CognirelTech-Quillpad-Server-002e98a/primaryHelper.py", line 227, in <module>
>     init()
>   File "/Users/MYUSER/Downloads/CognirelTech-Quillpad-Server-002e98a/primaryHelper.py", line 221, in init
>     d = loadedUniqueWords['tamil']
> KeyError: 'tamil'**
>

**Comment by saptha** [comment]
I also get this error.

**Comment by saptha** [comment]
This is resolved after unzipping the files as mentioned in the preparation steps
