### ISSUE TITLE
Can't able to load Unique words

### ISSUE THREAD

**Issue by Priyansh2** [CognirelTech/Quillpad-Server#8]
Warning: Nevow not found... continuing
Failed to load keyboard map file for gujarati. Exception [Errno 2] No such file or directory: 'unique_gujarati_words.txt'
Failed to load keyboard map file for bengali. Exception [Errno 2] No such file or directory: 'unique_bengali_words.txt'
Failed to load keyboard map file for telugu. Exception [Errno 2] No such file or directory: 'unique_telugu_words.txt'
Failed to load keyboard map file for malayalam. Exception [Errno 2] No such file or directory: 'unique_malayalam_words.txt'
Failed to load keyboard map file for marathi. Exception [Errno 2] No such file or directory: 'unique_marathi_words.txt'
Failed to load keyboard map file for nepali. Exception [Errno 2] No such file or directory: 'unique_nepali_words.txt'
Failed to load keyboard map file for kannada. Exception [Errno 2] No such file or directory: 'unique_kannada_words.txt'
Failed to load keyboard map file for tamil. Exception [Errno 2] No such file or directory: 'unique_tamil_words.txt'
Failed to load keyboard map file for punjabi. Exception [Errno 2] No such file or directory: 'unique_punjabi_words.txt'
Failed to load keyboard map file for hindi. Exception [Errno 2] No such file or directory: 'unique_hindi_words.txt'
Traceback (most recent call last):
  File "startquill_cherry.py", line 9, in <module>
    from QuillSourceProcessor import QuillSourceProcessor
  File "/home/priyansh/Downloads/research_ltrc_new_task/Quillpad-Server/QuillSourceProcessor.py", line 10, in <module>
    import primaryHelper
  File "/home/priyansh/Downloads/research_ltrc_new_task/Quillpad-Server/primaryHelper.py", line 227, in <module>
    init()
  File "/home/priyansh/Downloads/research_ltrc_new_task/Quillpad-Server/primaryHelper.py", line 221, in init
    d = loadedUniqueWords['hindi']
KeyError: 'hindi'

I have extracted all the files as told in the preparation steps . Also i have installed Pyrex as was referenced in this issue https://github.com/CognirelTech/Quillpad-Server/issues/4 . Please help me to resolve this

**Comment by Harish238** [comment]
All these files are extracted by default in a directory called "unique_word_files". Make sure you copy them to your working directory.
